### PR TITLE
Add support for Python 3.10-3.12 and drop EOL 3.5-3.7

### PR DESCRIPTION
**Pull request by hugovk**
Also modernise the GitHub Actions workflows and upgrade Python syntax with https://github.com/asottile/pyupgrade `--py38-plus`.

3.12 will fail until https://github.com/rabitt/pysox/pull/160 is merged; I can remove it from this PR if you want to merge this first.

### CODE REVIEW

**Comment by lostanlen** [comment]
Hello @hugovk, thank you for this. Indeed I was having issues with launching the GitHub action for your earlier PR

**Comment by lostanlen** [comment]
@hugovk sorry for the naive request but i can't seem to be able to merge this. Here's what i'm seeing:

Screenshot 2024-01-05 at 15 23 12

Is there a way i can bypass this "required" build of python 3.5?

Thanks

**Comment by hugovk** [comment]
Not a naive question at all! Do you have admin access to this repo?

If so, have a look at https://github.com/rabbit/pysox/settings/branches and there'll be a branch protection rule.

You can edit it and remove the rules for the old ones, and optionally add the new ones.

**Comment by lostanlen** [comment]
Thanks @hugovk. Looks like i'm maintainer but not admin. I have notified the admin, Rachel Bitner, over email. Will report back soon

**Pull request merged**
