### PR TITLE
 Allow trim to trim a file with just the start time

### LINKED ISSUE #82: Trim allows start time without an end
Trim can trim a file from the beginning with only the start time (e.g. `sox input output trim 10`) but pysox's trim requires both start and end. Added #81 as a fix.

### PR DESCRIPTION
**Pull request by stephwag**
Closes #82

### CODE REVIEW

**Comment by lostanlen** [comment]
The code LGTM but the docstring needs to be updated.
Also, could you please write a test for this new feature?

**Comment by lostanlen** [comment]
Nice. 

Can you please replace the following sentence to the docstring:
> Excerpt a clip from an audio file, given a start and end time.

by the following sentence:
> `Excerpt a clip from an audio file, given the start timestamp and end timestamp of the clip within the file, expressed in seconds. If the end timestamp is set to `None` or left unspecified, it defaults to the duration of the audio file.`

A message to the GitHub issue tracker bot: this PR fixes #81.

**Comment by lostanlen** [comment]
Also, a GitHub tip in case you didn't know: if you edit the original message of the PR (the one on the top, which is empty at the moment) and include the text "Closes #81" (or alternatively "Fixes #81"), then merging this PR will automatically close the corresponding issue you raised, because that text will be caught by the issue tracker bot of GitHub.

**Comment by stephwag** [comment]
@lostanlen Sounds good, added the updates.

**Comment by lostanlen** [comment]
@stephwag great job! thanks for the effort you put into it. I've just had an IRL conversation with @rabitt and she confirmed me that this PR is planned for pysox 1.4. She has a few things to sort out before scheduling that release, so this PR might remain open for a while, but we can consider that your job is done at this point. Don't hesitate to contribute again!
@rabitt this is read to merge IMO

**Comment by rabitt** [comment]
@stephwag thanks for this PR! Sorry for my delay in merging it, everything looks great. @lostanlen thanks for reviewing - I'll push this ahead of 1.4 to get it out!

**Pull request merged**
